service: demo-app
runtime: python310

automatic_scaling:
  target_cpu_utilization: 0.5
  min_idle_instances: 0 # アイドル時のインスタンスをゼロに設定
  max_idle_instances: 0 # 必要以上のアイドルインスタンスを作らない
  max_instances: 1 # 最大インスタンス数を1に制限

# entrypoint: gunicorn -b :$PORT main:app
entrypoint: python main.py

handlers:
  - url: /.*
    script: auto
